name: Github to Qase

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: cskmnrpt/qase-link-run@v2
      
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
      - name: Run Playwright tests
        env:
          QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
          QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TESTOPS_API_TOKEN }}
          QASE_TESTOPS_PROJECT: ${{ secrets.QASE_TESTOPS_PROJECT }}
          QASE_MODE: "testops"
          QASE_DEBUG: true

        run: |
          npx playwright test
          
      - name: List Environment Variables
        run: printenv
